#include "scene/scene_compile.h"

namespace lime {

std::string sceneBootLua(const std::string& startModule) {
    std::string out;
    out += "-- Generated by LimeVSC. Do not edit - regenerated on every build.\n";
    out += "--\n";
    out += "-- Loads the start scene and keeps it ticking. Requiring this module\n";
    out += "-- is all that starting an Engine-mode game takes, which is why the\n";
    out += "-- Start Scene node is a one-line require.\n";
    out += "\n";
    out += "local runtime = require(\"content.lime_scene\")\n";
    out += "local scene   = require(\"" + startModule + "\")\n";
    out += "\n";
    out += "local M = {}\n";
    out += "M.runtime = runtime\n";
    out += "M.world = runtime.load(scene)\n";
    out += "\n";
    out += "-- Hooked here rather than in a graph so a project keeps ticking even\n";
    out += "-- if its entry graph is rewritten. Behaviours run before anything a\n";
    out += "-- user graph hooks later, because this hook is registered first.\n";
    out += "Lime.onUpdate:hook(function(dt)\n";
    out += "  runtime.tick(M.world, dt)\n";
    out += "end)\n";
    out += "\n";
    out += "if Lime.onClose then\n";
    out += "  Lime.onClose:hook(function()\n";
    out += "    runtime.destroy(M.world)\n";
    out += "  end)\n";
    out += "end\n";
    out += "\n";
    out += "return M\n";
    return out;
}

}
