#include "scene/scene_compile.h"

#include <algorithm>
#include <sstream>

namespace lime {
namespace {

bool isIdent(const std::string& s) {
    if (s.empty()) return false;
    if (!std::isalpha(static_cast<unsigned char>(s[0])) && s[0] != '_') return false;
    for (char c : s)
        if (!std::isalnum(static_cast<unsigned char>(c)) && c != '_') return false;
    static const char* kReserved[] = {
        "and", "break", "do", "else", "elseif", "end", "false", "for",
        "function", "goto", "if", "in", "local", "nil", "not", "or",
        "repeat", "return", "then", "true", "until", "while"};
    for (const char* r : kReserved)
        if (s == r) return false;
    return true;
}

std::string key(const std::string& k) {
    if (isIdent(k)) return k;
    std::string q = "[\"";
    for (char c : k) {
        if (c == '"' || c == '\\') q += '\\';
        q += c;
    }
    return q + "\"]";
}

std::string quote(const std::string& s) {
    std::string q = "\"";
    for (char c : s) {
        if (c == '"' || c == '\\') q += '\\';
        if (c == '\n') { q += "\\n"; continue; }
        q += c;
    }
    return q + "\"";
}

std::string moduleFromGraphRef(std::string ref) {
    for (char& c : ref)
        if (c == '\\') c = '/';
    if (ref.size() > 5 && ref.compare(ref.size() - 5, 5, ".lime") == 0)
        ref.resize(ref.size() - 5);
    while (!ref.empty() && (ref.front() == '/' || ref.front() == '.'))
        ref.erase(ref.begin());
    if (ref.rfind("content/", 0) != 0) ref = "content/" + ref;
    for (char& c : ref)
        if (c == '/') c = '.';
    return ref;
}

}

namespace {

std::string resolveAsset(const std::string& value, const AssetDatabase* assets,
                         const std::string& entity, const std::string& comp,
                         const std::string& prop, Diagnostics& diag) {
    if (!assets) return value;
    const AssetGuid g = AssetDatabase::parseRef(value);
    if (!g.valid()) return value;

    const AssetRecord* rec = assets->find(g);
    if (!rec || rec->missing) {
        diag.error("entity '" + entity + "': " + comp + "." + prop
                   + " points at a missing asset"
                   + (rec ? " (was " + rec->relPath + ")" : "")
                   + " [" + g.str() + "]");
        return "nil";
    }
    const std::string path = "content/" + rec->relPath;
    std::string q = "\"";
    for (char c : path) {
        if (c == '"' || c == '\\') q += '\\';
        q += c;
    }
    return q + "\"";
}

}

std::vector<BrokenRef> findBrokenRefs(const Scene& s,
                                      const ComponentRegistry& comps,
                                      const AssetDatabase& assets) {
    std::vector<BrokenRef> out;
    for (const Entity& e : s.entities())
        for (const Component& c : e.components) {
            const ComponentDesc* d = comps.find(c.type);
            for (const auto& [k, v] : c.values) {
                if (d) {
                    const PropDesc* p = d->findProp(k);
                    if (!p || p->typeName.rfind("Asset:", 0) != 0) continue;
                }
                const AssetGuid g = AssetDatabase::parseRef(v);
                if (!g.valid()) continue;
                const AssetRecord* rec = assets.find(g);
                if (rec && !rec->missing) continue;
                out.push_back({e.name, c.type, k, g.str(),
                               rec ? rec->relPath : std::string()});
            }
        }
    return out;
}

SceneCompileResult compileScene(const Scene& s, const ComponentRegistry& comps,
                                const std::string& sourceName,
                                Diagnostics& diag, const AssetDatabase* assets) {
    SceneCompileResult r;

    std::vector<const Entity*> ordered;
    ordered.reserve(s.entities().size());
    for (const Entity& e : s.entities()) ordered.push_back(&e);
    std::sort(ordered.begin(), ordered.end(),
              [](const Entity* a, const Entity* b) { return a->id < b->id; });

    std::ostringstream o;
    o << "-- Generated by LimeVSC from " << sourceName << ". Do not edit.\n"
      << "--\n"
      << "-- Pure data: this module creates nothing. content.lime_scene walks\n"
      << "-- it and builds the world.\n\n"
      << "return {\n"
      << "  name = " << quote(s.name) << ",\n"
      << "  entities = {\n";

    for (const Entity* e : ordered) {
        o << "    {\n"
          << "      id = " << e->id.v << ",\n"
          << "      name = " << quote(e->name) << ",\n";
        if (e->parent.valid()) o << "      parent = " << e->parent.v << ",\n";

        std::vector<const Component*> cs;
        cs.reserve(e->components.size());
        for (const Component& c : e->components) cs.push_back(&c);
        std::stable_sort(cs.begin(), cs.end(),
                         [](const Component* a, const Component* b) {
                             return a->type < b->type;
                         });

        std::vector<const Component*> behaviours;
        std::vector<const Component*> plain;
        for (const Component* c : cs)
            (c->type == "Behaviour" ? behaviours : plain).push_back(c);

        o << "      components = {\n";
        for (const Component* c : plain) {
            const ComponentDesc* d = comps.find(c->type);
            if (!d)
                diag.warn("scene uses unknown component '" + c->type
                          + "' on entity '" + e->name
                          + "'; cooking it through unchanged");

            o << "        " << key(c->type) << " = {";
            std::vector<std::string> written;
            bool first = true;
            auto emit = [&](const std::string& k, const std::string& v) {
                o << (first ? " " : ", ") << key(k) << " = "
                  << resolveAsset(v, assets, e->name, c->type, k, diag);
                first = false;
                written.push_back(k);
            };
            if (d)
                for (const PropDesc& p : d->props) {
                    const std::string* set = c->value(p.name);
                    const std::string v = set ? *set : p.defaultValue;
                    if (v.empty()) continue;
                    emit(p.name, v);
                }
            for (const auto& [k, v] : c->values) {
                if (std::find(written.begin(), written.end(), k) != written.end())
                    continue;
                if (v.empty()) continue;
                emit(k, v);
            }
            o << (first ? "}," : " },") << "\n";
        }
        o << "      },\n";

        if (!behaviours.empty()) {
            o << "      behaviours = {\n";
            for (const Component* c : behaviours) {
                const std::string* graph = c->value("graph");
                std::string ref = graph ? *graph : std::string();
                if (ref.size() >= 2 && ref.front() == '"' && ref.back() == '"')
                    ref = ref.substr(1, ref.size() - 2);
                if (ref.empty()) {
                    diag.warn("entity '" + e->name
                              + "' has a Behaviour with no graph; skipping it");
                    continue;
                }
                o << "        { module = " << quote(moduleFromGraphRef(ref))
                  << ", props = {";
                bool first = true;
                for (const auto& [k, v] : c->values) {
                    if (k == "graph" || v.empty()) continue;
                    o << (first ? " " : ", ") << key(k) << " = " << v;
                    first = false;
                }
                o << (first ? "} },\n" : " } },\n");
            }
            o << "      },\n";
        }
        o << "    },\n";
    }

    o << "  },\n}\n";
    r.lua = o.str();
    r.ok = !diag.hasErrors();
    return r;
}

std::string sceneRuntimeLua() {
    return
        "-- LimeVSC scene runtime.\n"
        "--\n"
        "-- Walks a cooked scene table and builds the world from it. This is the\n"
        "-- ONE place that knows which engine call a component maps to, which is\n"
        "-- why it ships as editable Lua rather than being generated: retarget\n"
        "-- the whole scene format by editing this file.\n"
        "--\n"
        "-- LimeVSC will not overwrite this file once it exists, so local edits\n"
        "-- survive every rebuild.\n"
        "--\n"
        "-- The tick loop is parallel arrays rather than a list of {module, entity}\n"
        "-- pairs on purpose. Gameplay is Lua, so the lever that remains is keeping\n"
        "-- the per-frame path free of allocation: two flat arrays indexed by one\n"
        "-- integer beat an array of tables, and nothing here builds a table per\n"
        "-- entity per frame.\n"
        "\n"
        "local M = {}\n"
        "\n"
        "-- component name -> function(entity, props). Add to this table to teach\n"
        "-- the runtime a component your game declared.\n"
        "M.builders = {}\n"
        "\n"
        "function M.builders.Transform(e, p)\n"
        "  e.position = p.position\n"
        "  e.rotation = p.rotation\n"
        "  e.scale    = p.scale\n"
        "end\n"
        "\n"
        "function M.builders.MeshRenderer(e, p)\n"
        "  if p.mesh and p.mesh ~= \"\" then\n"
        "    e.mesh = Mesh(p.mesh)\n"
        "    if e.mesh and p.visible == false then e.mesh:hide() end\n"
        "  end\n"
        "end\n"
        "\n"
        "function M.builders.Tag(e, p)\n"
        "  e.tags = e.tags or {}\n"
        "  if p.name and p.name ~= \"\" then e.tags[p.name] = true end\n"
        "end\n"
        "\n"
        "-- Instantiates one scene table. Returns the entities indexed by scene id\n"
        "-- and by name, plus the flat arrays the tick loop walks.\n"
        "function M.load(scene)\n"
        "  local world = {\n"
        "    name = scene.name, byId = {}, byName = {},\n"
        "    tickFn = {}, tickSelf = {}, tickCount = 0,\n"
        "    all = {}, count = 0,\n"
        "  }\n"
        "\n"
        "  local entities = scene.entities or {}\n"
        "  for i = 1, #entities do\n"
        "    local spec = entities[i]\n"
        "    local e = { id = spec.id, name = spec.name, components = spec.components }\n"
        "    world.byId[spec.id] = e\n"
        "    world.byName[spec.name] = e\n"
        "    world.count = world.count + 1\n"
        "    world.all[world.count] = e\n"
        "  end\n"
        "\n"
        "  -- Parents in a second pass: a child may appear before its parent.\n"
        "  for i = 1, #entities do\n"
        "    local spec = entities[i]\n"
        "    if spec.parent then world.byId[spec.id].parent = world.byId[spec.parent] end\n"
        "  end\n"
        "\n"
        "  for i = 1, #entities do\n"
        "    local spec = entities[i]\n"
        "    local e = world.byId[spec.id]\n"
        "    for name, props in pairs(spec.components or {}) do\n"
        "      local build = M.builders[name]\n"
        "      if build then build(e, props) end\n"
        "    end\n"
        "  end\n"
        "\n"
        "  -- Behaviours last, so On Spawn sees a fully built world.\n"
        "  for i = 1, #entities do\n"
        "    local spec = entities[i]\n"
        "    local e = world.byId[spec.id]\n"
        "    local list = spec.behaviours\n"
        "    for j = 1, (list and #list or 0) do\n"
        "      local b = list[j]\n"
        "      local ok, mod = pcall(require, b.module)\n"
        "      if not ok then\n"
        "        print(\"scene: cannot load behaviour \" .. b.module)\n"
        "      else\n"
        "        -- Property overrides land directly on the entity, so a graph reads\n"
        "        -- them as self.<name> with no lookup layer in between.\n"
        "        for k, v in pairs(b.props or {}) do e[k] = v end\n"
        "        if mod.onSpawn then mod.onSpawn(e) end\n"
        "        if mod.onTick then\n"
        "          -- The module table is shared by every entity using this\n"
        "          -- behaviour; only the function reference and the entity handle\n"
        "          -- are stored per instance.\n"
        "          local n = world.tickCount + 1\n"
        "          world.tickCount = n\n"
        "          world.tickFn[n] = mod.onTick\n"
        "          world.tickSelf[n] = e\n"
        "        end\n"
        "        e.behaviours = e.behaviours or {}\n"
        "        e.behaviours[#e.behaviours + 1] = mod\n"
        "      end\n"
        "    end\n"
        "  end\n"
        "\n"
        "  return world\n"
        "end\n"
        "\n"
        "-- The hot path. The arrays are hoisted into locals because a table index\n"
        "-- per iteration is what shows up at ten thousand entities.\n"
        "function M.tick(world, dt)\n"
        "  local fn, subject, n = world.tickFn, world.tickSelf, world.tickCount\n"
        "  for i = 1, n do\n"
        "    fn[i](subject[i], dt)\n"
        "  end\n"
        "end\n"
        "\n"
        "function M.destroy(world)\n"
        "  for i = 1, world.count do\n"
        "    local e = world.all[i]\n"
        "    local list = e.behaviours\n"
        "    for j = 1, (list and #list or 0) do\n"
        "      if list[j].onDestroy then list[j].onDestroy(e) end\n"
        "    end\n"
        "  end\n"
        "end\n"
        "\n"
        "return M\n";
}

}
