-- Generated by LimeVSC from branch.lime -- do not edit
Lime.onStart:hook(function()
  local compute = test.compute()
  if compute > 10 then
    test.log("big")
  else
    test.log("small")
  end
  test.log("done")
end)
