#include "limecore.h"

#include <cctype>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <string>

namespace lime {
namespace {

using EK = LuaAst::EK;
using SK = LuaAst::SK;

int precedence(const std::string& op) {
    if (op == "or") return 1;
    if (op == "and") return 2;
    if (op == "<" || op == ">" || op == "<=" || op == ">=" || op == "~=" || op == "==")
        return 3;
    if (op == "|") return 4;
    if (op == "~") return 5;
    if (op == "&") return 6;
    if (op == "<<" || op == ">>") return 7;
    if (op == "..") return 8;
    if (op == "+" || op == "-") return 9;
    if (op == "*" || op == "/" || op == "//" || op == "%") return 10;
    if (op == "^") return 12;
    return 0;
}

constexpr int kUnaryPrec = 11;
constexpr int kAtomPrec  = 99;

bool rightAssociative(const std::string& op) { return op == ".." || op == "^"; }

bool isIdentifier(const std::string& s) {
    if (s.empty()) return false;
    if (!(std::isalpha(static_cast<unsigned char>(s[0])) || s[0] == '_')) return false;
    for (char c : s)
        if (!(std::isalnum(static_cast<unsigned char>(c)) || c == '_')) return false;
    static const char* kw[] = {"and", "break", "do", "else", "elseif", "end",
                               "false", "for", "function", "goto", "if", "in",
                               "local", "nil", "not", "or", "repeat", "return",
                               "then", "true", "until", "while"};
    for (const char* k : kw) if (s == k) return false;
    return true;
}

bool isAtomicLua(const std::string& s) {
    if (s.empty()) return false;
    if (s == "true" || s == "false" || s == "nil") return true;

    if ((s.front() == '"' && s.back() == '"') ||
        (s.front() == '\'' && s.back() == '\'')) {
        if (s.size() < 2) return false;
        for (std::size_t i = 1; i + 1 < s.size(); ++i) {
            if (s[i] == '\\') { ++i; continue; }
            if (s[i] == s.front()) return false;
        }
        return true;
    }

    {
        char* end = nullptr;
        std::strtod(s.c_str(), &end);
        if (end && *end == '\0' && end != s.c_str()) return true;
    }

    bool startOfPart = true;
    for (char c : s) {
        if (startOfPart) {
            if (!(std::isalpha(static_cast<unsigned char>(c)) || c == '_')) return false;
            startOfPart = false;
        } else if (c == '.') {
            startOfPart = true;
        } else if (!(std::isalnum(static_cast<unsigned char>(c)) || c == '_')) {
            return false;
        }
    }
    return !startOfPart;
}

std::string quote(const std::string& s) {
    std::string out = "\"";
    for (char c : s) {
        switch (c) {
        case '"':  out += "\\\""; break;
        case '\\': out += "\\\\"; break;
        case '\n': out += "\\n"; break;
        case '\r': out += "\\r"; break;
        case '\t': out += "\\t"; break;
        default:
            if (static_cast<unsigned char>(c) < 0x20) {
                char buf[8];
                std::snprintf(buf, sizeof(buf), "\\%d", static_cast<int>(c));
                out += buf;
            } else {
                out += c;
            }
        }
    }
    return out + "\"";
}

std::string formatNumber(double d) {
    if (std::isfinite(d) && d == std::floor(d) && std::fabs(d) < 1e15) {
        char buf[32];
        std::snprintf(buf, sizeof(buf), "%lld", static_cast<long long>(d));
        return buf;
    }
    char buf[40];
    std::snprintf(buf, sizeof(buf), "%.14g", d);
    return buf;
}

class Printer {
public:
    Printer(const LuaAst& ast, const PrintOptions& opts, SourceMap* map)
        : ast_(ast), opts_(opts), map_(map) {}

    std::string run(StmtRef root) {
        if (opts_.emitHeader) {
            out_ += "-- Generated by LimeVSC";
            if (!opts_.headerSourceName.empty()) out_ += " from " + opts_.headerSourceName;
            out_ += " -- do not edit\n";
            ++line_;
        }
        const LuaAst::StmtNode& r = ast_.stmt(root);
        if (r.kind == SK::Block) {
            for (StmtRef s : r.kids) stmt(s, 0);
        } else {
            stmt(root, 0);
        }
        return out_;
    }

private:
    void indent(int depth) { out_.append(static_cast<std::size_t>(depth * opts_.indentWidth), ' '); }

    void newline() { out_ += '\n'; ++line_; }

    void mark(const LuaAst::StmtNode& n) {
        if (map_ && n.attr.valid()) map_->lines.emplace_back(line_, n.attr);
    }

    void body(StmtRef s, int depth) {
        const LuaAst::StmtNode& n = ast_.stmt(s);
        if (n.kind == SK::Block) {
            for (StmtRef k : n.kids) stmt(k, depth);
        } else {
            stmt(s, depth);
        }
    }

    void stmt(StmtRef s, int depth) {
        const LuaAst::StmtNode& n = ast_.stmt(s);
        curDepth_ = depth;
        switch (n.kind) {
        case SK::Blank:
            newline();
            return;

        case SK::Comment:
            mark(n);
            indent(depth);
            out_ += "-- " + n.text;
            newline();
            return;

        case SK::Block:
            mark(n);
            indent(depth); out_ += "do"; newline();
            for (StmtRef k : n.kids) stmt(k, depth + 1);
            indent(depth); out_ += "end"; newline();
            return;

        case SK::ExprStat:
            mark(n);
            indent(depth);
            expr(n.exprs.empty() ? ExprRef{} : n.exprs[0], 0);
            newline();
            return;

        case SK::Local: {
            mark(n);
            indent(depth);
            out_ += "local ";
            for (std::size_t i = 0; i < n.names.size(); ++i) {
                if (i) out_ += ", ";
                out_ += n.names[i];
            }
            if (!n.exprs.empty()) {
                out_ += " = ";
                for (std::size_t i = 0; i < n.exprs.size(); ++i) {
                    if (i) out_ += ", ";
                    expr(n.exprs[i], 0);
                }
            }
            newline();
            return;
        }

        case SK::Assign: {
            mark(n);
            indent(depth);
            const std::size_t t = static_cast<std::size_t>(n.count);
            for (std::size_t i = 0; i < t && i < n.exprs.size(); ++i) {
                if (i) out_ += ", ";
                expr(n.exprs[i], 0);
            }
            out_ += " = ";
            for (std::size_t i = t; i < n.exprs.size(); ++i) {
                if (i > t) out_ += ", ";
                expr(n.exprs[i], 0);
            }
            newline();
            return;
        }

        case SK::If: {
            mark(n);
            const std::size_t arms = n.exprs.size();
            for (std::size_t i = 0; i < arms; ++i) {
                indent(depth);
                out_ += (i == 0) ? "if " : "elseif ";
                expr(n.exprs[i], 0);
                out_ += " then";
                newline();
                if (i < n.kids.size()) body(n.kids[i], depth + 1);
            }
            if (n.kids.size() > arms) {
                indent(depth); out_ += "else"; newline();
                body(n.kids[arms], depth + 1);
            }
            indent(depth); out_ += "end"; newline();
            return;
        }

        case SK::While:
            mark(n);
            indent(depth); out_ += "while ";
            expr(n.exprs.empty() ? ExprRef{} : n.exprs[0], 0);
            out_ += " do"; newline();
            if (!n.kids.empty()) body(n.kids[0], depth + 1);
            indent(depth); out_ += "end"; newline();
            return;

        case SK::Repeat:
            mark(n);
            indent(depth); out_ += "repeat"; newline();
            if (!n.kids.empty()) body(n.kids[0], depth + 1);
            indent(depth); out_ += "until ";
            expr(n.exprs.empty() ? ExprRef{} : n.exprs[0], 0);
            newline();
            return;

        case SK::NumFor:
            mark(n);
            indent(depth);
            out_ += "for " + (n.names.empty() ? std::string("i") : n.names[0]) + " = ";
            for (std::size_t i = 0; i < n.exprs.size(); ++i) {
                if (i) out_ += ", ";
                expr(n.exprs[i], 0);
            }
            out_ += " do"; newline();
            if (!n.kids.empty()) body(n.kids[0], depth + 1);
            indent(depth); out_ += "end"; newline();
            return;

        case SK::GenFor:
            mark(n);
            indent(depth);
            out_ += "for ";
            for (std::size_t i = 0; i < n.names.size(); ++i) {
                if (i) out_ += ", ";
                out_ += n.names[i];
            }
            out_ += " in ";
            for (std::size_t i = 0; i < n.exprs.size(); ++i) {
                if (i) out_ += ", ";
                expr(n.exprs[i], 0);
            }
            out_ += " do"; newline();
            if (!n.kids.empty()) body(n.kids[0], depth + 1);
            indent(depth); out_ += "end"; newline();
            return;

        case SK::Return:
            mark(n);
            indent(depth);
            out_ += "return";
            for (std::size_t i = 0; i < n.exprs.size(); ++i) {
                out_ += (i ? ", " : " ");
                expr(n.exprs[i], 0);
            }
            newline();
            return;

        case SK::Break:
            mark(n);
            indent(depth); out_ += "break"; newline();
            return;

        case SK::Goto:
            mark(n);
            indent(depth); out_ += "goto " + n.text; newline();
            return;

        case SK::Label:
            mark(n);
            indent(depth > 0 ? depth - 1 : 0);
            out_ += "::" + n.text + "::";
            newline();
            return;

        case SK::Func:
            mark(n);
            indent(depth);
            out_ += "function " + n.text + "(";
            for (std::size_t i = 0; i < n.names.size(); ++i) {
                if (i) out_ += ", ";
                out_ += n.names[i];
            }
            out_ += ")"; newline();
            if (!n.kids.empty()) body(n.kids[0], depth + 1);
            indent(depth); out_ += "end"; newline();
            return;

        case SK::LocalFunc:
            mark(n);
            indent(depth);
            out_ += "local function " + n.text + "(";
            for (std::size_t i = 0; i < n.names.size(); ++i) {
                if (i) out_ += ", ";
                out_ += n.names[i];
            }
            out_ += ")"; newline();
            if (!n.kids.empty()) body(n.kids[0], depth + 1);
            indent(depth); out_ += "end"; newline();
            return;
        }
    }

    void expr(ExprRef e, int parentPrec, bool rightOfSameOp = false) {
        const LuaAst::ExprNode& n = ast_.expr(e);
        switch (n.kind) {
        case EK::Name:    out_ += n.text; return;
        case EK::Nil:     out_ += "nil"; return;
        case EK::Bool:    out_ += n.b ? "true" : "false"; return;
        case EK::Number:  out_ += formatNumber(n.num); return;
        case EK::String:  out_ += quote(n.text); return;
        case EK::Varargs: out_ += "..."; return;

        case EK::Raw:
            if (parentPrec > 0 && !isAtomicLua(n.text)) out_ += "(" + n.text + ")";
            else                                        out_ += n.text;
            return;

        case EK::Binop: {
            const int p = precedence(n.text);
            const bool wrap = p < parentPrec
                              || (p == parentPrec && rightOfSameOp
                                  && !rightAssociative(n.text));
            if (wrap) out_ += '(';
            const bool ra = rightAssociative(n.text);
            expr(n.kids[0], ra ? p + 1 : p);
            out_ += ' ' + n.text + ' ';
            expr(n.kids[1], ra ? p : p, !ra);
            if (wrap) out_ += ')';
            return;
        }

        case EK::Unop: {
            const bool wrap = kUnaryPrec < parentPrec;
            if (wrap) out_ += '(';
            out_ += n.text;
            if (n.text == "not") out_ += ' ';
            expr(n.kids[0], kUnaryPrec);
            if (wrap) out_ += ')';
            return;
        }

        case EK::Field:
            expr(n.kids[0], kAtomPrec);
            if (isIdentifier(n.text)) out_ += '.' + n.text;
            else                      out_ += '[' + quote(n.text) + ']';
            return;

        case EK::Index:
            expr(n.kids[0], kAtomPrec);
            out_ += '[';
            expr(n.kids[1], 0);
            out_ += ']';
            return;

        case EK::Call:
            expr(n.kids[0], kAtomPrec);
            out_ += '(';
            for (std::size_t i = 1; i < n.kids.size(); ++i) {
                if (i > 1) out_ += ", ";
                expr(n.kids[i], 0);
            }
            out_ += ')';
            return;

        case EK::Method:
            expr(n.kids[0], kAtomPrec);
            out_ += ':' + n.text + '(';
            for (std::size_t i = 1; i < n.kids.size(); ++i) {
                if (i > 1) out_ += ", ";
                expr(n.kids[i], 0);
            }
            out_ += ')';
            return;

        case EK::Function: {
            out_ += "function(";
            for (std::size_t i = 0; i < n.params.size(); ++i) {
                if (i) out_ += ", ";
                out_ += n.params[i];
            }
            out_ += ')';
            newline();
            const int outer = curDepth_;
            body(n.body, outer + 1);
            curDepth_ = outer;
            indent(outer);
            out_ += "end";
            return;
        }

        case EK::Table: {
            out_ += '{';
            for (std::size_t i = 0; i < n.kids.size(); ++i) {
                if (i) out_ += ", ";
                if (i < n.params.size() && !n.params[i].empty()) {
                    if (isIdentifier(n.params[i])) out_ += n.params[i] + " = ";
                    else out_ += '[' + quote(n.params[i]) + "] = ";
                }
                expr(n.kids[i], 0);
            }
            out_ += '}';
            return;
        }
        }
    }

    const LuaAst&      ast_;
    const PrintOptions& opts_;
    SourceMap*         map_;
    std::string        out_;
    int                line_ = 1;
    int                curDepth_ = 0;
};

}

std::string printLua(const LuaAst& ast, StmtRef root, const PrintOptions& opts,
                     SourceMap* mapOut) {
    if (mapOut) mapOut->lines.clear();
    Printer p(ast, opts, mapOut);
    return p.run(root);
}

}
